version: '3'
services:
  quorum:
    env_file: environment.env
    build: 
      context: .
      args:
        - CVER=0.3.2
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.1.0
    network_mode: "host"
    ports:
     - "21000:21000"
     - "8545:8545"
     - "50401:50401"
     - "8546:8546"
     - "9001:9001"
    volumes:
     - /home/rashid/quorum_1node/data/d1:/quorum/data
     - /home/rashid/quorum_1node/logs/l1:/quorum/logs
  quorum2:
    env_file: environment2.env
    build: 
      context: .
      args:
        - CVER=0.3.2
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.1.0
    network_mode: "host"
    ports:
     - "21000:21001"
     - "8545:8547"
     - "50401:50402"
     - "8546:8548"
     - "9001:9002"
    volumes:
     - /home/rashid/quorum_1node/data/d2:/quorum/data
     - /home/rashid/quorum_1node/logs/l2:/quorum/logs
   quorum3:
    env_file: environment3.env
    build: 
      context: .
      args:
        - CVER=0.3.2
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.1.0
    network_mode: "host"
    ports:
     - "21000:21002"
     - "8545:8549"
     - "50401:50403"
     - "8546:8550"
     - "9001:9003"
    volumes:
     - /home/rashid/quorum_1node/data/d3:/quorum/data
     - /home/rashid/quorum_1node/logs/l3:/quorum/logs 