version: '3'
services:
  quorum:
    environment:
     - DATA_DIR=data
     - LOG_DIR=logs
     - CONSTELLATION_PORT=9001
     - CONSTELLATION_ADDRESS=http://127.0.0.1:9001/
     - OTHER_CONSTELLATION_NODES=http://127.0.0.1:9001/
     - RPC_PORT=8545
     - WS_PORT=8546
     - RAFT_PORT=50401
     - GETH_PORT=21000
    build: 
      context: .
      args:
        - CVER=0.3.2
        - CREL=constellation-0.3.2-ubuntu1604
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.0.2
    ports:
     - "21000:21000"
     - "8545:8545"
     - "50401:50401"
     - "8546:8546"
    volumes:
     - /home/rashid/quorum_1node/data:/quorum/data
     - /home/rashid/quorum_1node/logs:/quorum/logs