version: '3'
services:
  quorum:
    env_file: environment.env
    build: 
      context: .
      args:
        - CVER=0.3.2
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.1.0
    network_mode: "host"
    # Host Port - Target Port
    ports:
     - "21000:21000"
     - "8545:8545"
     - "50401:50401"
     - "8546:8546"
     - "9001:9001"
    #Host Directory - Target Directory
    volumes:
     - /data:/quorum/data
     - /data/logs:/quorum/logs
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
