version: '3'
services:
  #Quorum Node 1
  quorum:
    env_file: environment.env
    build: 
      context: .
      args:
        - CVER=0.3.2
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.1.0
    networks: 
      internal:
        ipv4_address: 10.0.0.1
    ports:
     - "21000:21000"
     - "8545:8545"
     - "50401:50401"
     - "8546:8546"
     - "9001:9001"
    volumes:
     - /data/d1:/quorum/data
     - /data/logs/l1:/quorum/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  #Quorum Node 2
  quorum2:
    env_file: environment2.env
    build: 
      context: .
      args:
        - CVER=0.3.2
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.1.0
    networks: 
      internal:
        ipv4_address: 10.0.0.2
    depends_on:
     - quorum
    ports:
     - "21001:21001"
     - "8547:8547"
     - "50402:50402"
     - "8548:8548"
     - "9002:9002"
    volumes:
     - /data/d2:/quorum/data
     - /data/logs/l2:/quorum/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  #Quorum Node 3
  quorum3:
    env_file: environment3.env
    build: 
      context: .
      args:
        - CVER=0.3.2
        - GOREL=go1.9.3.linux-amd64.tar.gz
        - QVER=v2.1.0
    networks: 
      internal:
        ipv4_address: 10.0.0.3
    depends_on:
     - quorum
    ports:
     - "21002:21002"
     - "8549:8549"
     - "50403:50403"
     - "8550:8550"
     - "9003:9003"
    volumes:
     - /data/d3:/quorum/data
     - /data/logs/l3:/quorum/logs
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s 

networks: 
  internal:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/8